djangoapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

app_name = 'djangoapp'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^polls/', include('polls.urls'), name="polls"),
    url(r'^todo/', include('todo.urls'), name="todo"),
    url(r'^admin/', admin.site.urls, name="admin"),
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^(?P<pk>\d+)/results', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote', views.vote, name='vote'),
    url(r'^(?P<pk>\d+)', views.DetailView.as_view(), name='detail'),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

todo/urls.py
from django.conf.urls import url
from . import views

app_name = 'todo'
urlpatterns = [
    url(r'^(?P<task_id>\d+)/done', views.done, name='done'),
    url(r'^(?P<pk>\d+)', views.DetailView.as_view(), name='detail'),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

polls/models.py
# -*- coding: utf-8 -*-
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

todo/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

class Task(models.Model):
    summary = models.CharField(max_length=60)
    due_date = models.DateTimeField()
    PRIORITIES = (
        (0, 'urgent'),
        (1, 'high'),
        (2, 'medium'),
        (3, 'low'),
    )
    priority = models.IntegerField(
        choices=PRIORITIES,
        default=3,
    )
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.summary

    def is_completed(self):
        return self.completed

    #TODO: raise exception if task is already completed
    def complete(self):
        self.completed = True
        self.save()

djangoapp/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

def index(request):
    return render(request, 'index.html')

polls/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import *


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

todo/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import *


class IndexView(generic.ListView):
    template_name = 'todo/index.html'
    context_object_name = 'todo_list'

    def get_queryset(self):
        return Task.objects.order_by('-priority')


class DetailView(generic.DetailView):
    model = Task
    template_name = 'todo/detail.html'


def done(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if task.is_completed():
        return render(request, 'todo/detail.html', {
            'task': task,
            'error_message':"Can't complete a task that's alreadycompleted!",
        })
    else:
        task.complete()
        return HttpResponseRedirect(reverse('todo:detail', args=(task.id,)))

djangoapp/templates/index.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="container">
<h3>Welcome to my Django apps page</h3>
<ul>
<li><a href="{% url 'polls:index' %}">polls</a></li>
<li><a href="{% url 'todo:index' %}">todo</a></li>
<li><a href="{% url 'admin:index' %}">admin</a></li>
</ul>
</div>

polls/templates/polls/detail.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="container-fluid">
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
<div class="well">
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
</div>
</div>

polls/templates/polls/index.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="container-fluid">
<h1> Recent polls: </h1>
{% if latest_question_list %}
    <div class="row">
    {% for question in latest_question_list %}
        <div class="col-md-4"><div class="well">
		<a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
		</div></div>
    {% endfor %}
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>

polls/templates/polls/results.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<h1>{{ question.question_text }}</h1>

<div class="container-fluid well">
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
</div>

<div style="text-align: center;">
<a href="{% url 'polls:detail' question.id %}">Vote again?</a><br>
<a href="{% url 'polls:index' %}">Go back to polls</a>
</div>

todo/templates/todo/detail.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="container-fluid">
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
<div class="well">
<h3>{{ task.summary }}</h3>
<p> {{ task.due_date }} </p>
<p> Priority: {{ task.get_priority_display }} </p>
{% if not task.completed %}
<a href="{% url 'todo:done' task.id %}">Set as completed</a>
{% endif %} 
</div>
</div>

todo/templates/todo/index.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

{% if todo_list %}
	<div class="container-fluid">
	<h1> TODO List </h1>
	<div class="list-group">
		{% for task in todo_list %}
			<div class="list-group-item">
				<a href="{% url 'todo:detail' task.id %}">{{ task.summary }}</a>
			<div>
		{% endfor %}
	</div>
	</div>
{% else %}
	<div class="well">	
		<p> No tasks available </p>
	</div>
{% endif %}